routes/web.php
<?php

use App\Http\Controllers\AlumnoController;
use App\Http\Controllers\EmpleadoController;
use App\Http\Controllers\GrupoController;

use App\Http\Controllers\ClaseController;
use App\Http\Controllers\HorarioController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

//Para que si ponemos la ruta principal haya que iniciar sesion en la pagina
Route::get('/', function () {
    return view('auth.login');
});


//Cuando escribamos en la url empleados nos redirige a la vista index de empleados
Route::get("/empleados", function() {
    return view('empleados.index');
});


//Obtenemos automaticamente las rutas asociadas a empleados
Route::resource('empleados', EmpleadoController::class)->middleware('auth');

//Hacemos que desaparezca el boton de registro de usuario y de restablecer la contraseña
Auth::routes(['register'=>true, 'reset' => false]);


//Hacemos que se redirija al index global cuando se inicie sesion
Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', function(){
        return view('index');
    })->name('home');
});
Route::group(['middleware' => 'auth'], function() {
    Route::get('/', function () {
        return view('index');
    })->name('home2');
});
//Asignando ruta para la busqueda de alumno
Route::get("/alumnos/search", function () {
    return view('alumnos.search');
})->name('alumnos.search')->middleware('auth');
Route::get('/alumnos/searchAlumno', [AlumnoController::class, 'buscarAlumno']);

Route::get('/grupos-clases/grupos/{grupo}/mostrar-alumnos', [GrupoController::class, 'mostrarAlumnos'])->name('grupos.mostrar-alumnos')->middleware('auth');

Route::get('/alumnos/{grupo}/mostrar-alumnos', [AlumnoController::class, 'mostrarAlumnos'])->name('alumnos.mostrar-alumnos')->middleware('auth');

Route::get("/grupos-clases/grupos/{grupo}/asignar-alumnos", [GrupoController::class, 'asignarAlumnos'])->name('grupos.asignar-alumnos')->middleware('auth');





//Ruta para acceder al formulario de edicion del registro
Route::get("horarios/edit/{dia}/{tramo}/{fecha}/{id}", [HorarioController::class, 'edit']);

//Ruta para acceder al formulario de Horario(create) mediante el botón disponible en la casilla vacia del horario
Route::get("horarios/create/{dia}/{tramo}/{fecha}", [HorarioController::class, 'createPredefinido']);

Route::resource('alumnos', AlumnoController::class)->middleware('auth');

Route::resource('grupos-clases/clases', ClaseController::class)->middleware('auth');

Route::resource('grupos-clases/grupos', GrupoController::class)->middleware('auth');

Route::resource('grupos-clases', GrupoController::class)->middleware('auth');

Route::resource('horarios', HorarioController::class)->middleware('auth');


//Para acceder a la funcion asociada a buscar el alumno
/** Route::get('/alumnos/searchAlumno', [AlumnoController::class, 'buscarAlumno']);


//Para asociar todas las rutas de alumnos
Route::resource('alumnos', AlumnoController::class)->middleware('auth');


//Para asociar todas las rutas de grupos

Route::get('/grupos-clases/grupos/{grupo}/mostrar-alumnos', [GrupoController::class, 'mostrarAlumnos'])->name('grupos.mostrar-alumnos')->middleware('auth');
Route::get('/alumnos/{grupo}/mostrar-alumnos', [AlumnoController::class, 'mostrarAlumnos'])->name('alumnos.mostrar-alumnos')->middleware('auth');
Route::get("/grupos-clases/grupos/{grupo}/asignar-alumnos", [GrupoController::class, 'asignarAlumnos'])->name('grupos.asignar-alumnos')->middleware('auth');
Route::get("/grupos-clases/grupos/{grupo}/edit", [GrupoController::class, 'edit'])->name('grupos.edit')->middleware('auth');



Route::resource('grupos-clases/clases', AlumnoController::class);

//Redireccionar a la vista de horarios
Route::get('/horarios', function() {
    return view('horarios');
});*/

app/Models/Horario.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Horario extends Model
{
    use HasFactory;

    protected $fillable = ['codigoClase', 'codigoEmpleado', 'codigoGrupo', 'diaSemana', 'horaInicio', 'horaFin', 'primerDia', 'repetir', 'repeticiones'];

    public function obtenerCodigoClase()
    {
        return $this->belongsTo(Clase::class, 'nombre'); // Asegúrate de que 'codigoClase' sea la columna correcta para la relación.
    }

    public function obtenerCodigoEmpleado()
    {
        return $this->belongsTo(Empleado::class, 'nombre'); // Asegúrate de que 'codigoEmpleado' sea la columna correcta para la relación.
    }
    public function obtenerNombreClase()
    {
        echo "hola";
    }

    public function clase()
    {
        return $this->belongsTo('App\Models\Clase', 'codigoClase', 'id');
    }

}

app/Http/Controllers/HorarioController.php
<?php

namespace App\Http\Controllers;

use App\Models\Horario;
use App\Models\Clase;
use App\Models\Empleado;
use App\Models\Grupo;
use App\Rules\ValidacionRegistro;
use Illuminate\Http\Request;
use Carbon\Carbon;
use PhpParser\Comment;
use DateTime;

class HorarioController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        Carbon::setWeekStartsAt(Carbon::MONDAY);
        Carbon::setWeekEndsAt(Carbon::SUNDAY);

        //Recogemos el valor del input de la semana escogida
        $semana = $request->input('semana');
        $currentDate = Carbon::parse($semana);
        if ($semana) {

            // Para encontrar el inicio de la semana (Lunes)
            $startOfWeek = date('Y-m-d', strtotime('monday this week', strtotime($semana)));
            $endOfWeek = date('Y-m-d', strtotime('sunday this week', strtotime($semana)));

            //Debug
            //echo "Inicio de la semana: $startOfWeek";
            //echo "Fin de la semana: $endOfWeek";

            $horarios = Horario::with('clase')
                ->whereBetween('primerDia', [$startOfWeek, $endOfWeek])
                ->orderBy('primerDia', 'asc')
                ->orderBy('horaInicio', 'asc')
                ->get();

            //dd($horarios);
            return view('horarios.index', [
                'horarios' => $horarios,
                'currentDate' => $currentDate,
            ]);
        } else {
            // Tomamos la fecha del request o la fecha actual si no se provee ninguna
            $date = $request->input('date', Carbon::now()->toDateString());
            $currentDate = Carbon::parse($date);

            $startOfWeek = clone $currentDate;
            $startOfWeek->startOfWeek();
            $endOfWeek = clone $currentDate;
            $endOfWeek->endOfWeek();

            // Verifica las fechas antes de hacer la consulta
            //dd($currentDate->toDateString(), $startOfWeek->toDateString(), $endOfWeek->toDateString());

            $horarios = Horario::with('clase')
                ->whereBetween('primerDia', [$startOfWeek, $endOfWeek])
                ->orderBy('primerDia', 'asc')
                ->orderBy('horaInicio', 'asc')
                ->get();

            return view('horarios.index', [
                'horarios' => $horarios,
                'currentDate' => $currentDate,
            ]);
        }


    }





    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $clases = Clase::all();
        $empleados = Empleado::all();
        $grupos = Grupo::all();
        return view('horarios.create', compact('clases', 'empleados', 'grupos', ));
    }


    public function createPredefinido($dia, $tramo, $fecha)
    {
        //Decodificar la variable tramo enviada por url
        $tramo = urldecode($tramo);

        //Agrupar las variables en un array
        $datos = [
            'dia' => $dia,
            'tramo' => $tramo,
            'fecha' => $fecha
        ];


        $clases = Clase::all();
        $empleados = Empleado::all();
        $grupos = Grupo::all();
        return view('horarios.create', compact('clases', 'empleados', 'grupos', 'datos'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        if($this->comprobarExistencia($request)){
            return back()->with('error', 'Ya existe un registro con el mismo primer dia y tramo horario');
        }
        
        try {
            //VALIDACION DE DATOS ENVIADOS
            //dd(request()->all());
            //Tramos horarios existentes, futuro configurables
            $tramos = [
                ['10:00', '11:20'],
                ['11:30', '12:50'],
                ['13:00', '14:20'],
                ['15:00', '16:20'],
                ['16:30', '17:50'],
                ['18:00', '19:20'],
                ['19:30', '20:50']
            ];

            //Convierto el array a String separado por ' --- '
            $tramoString = array_map(function ($tramo) {
                return implode(' --- ', $tramo);
            }, $tramos);

            //Requisitos de los campos del formulario
            $campos = [
                'codigoClase' => 'required|integer',
                'codigoEmpleado' => 'required|integer',
                'codigoGrupo' => 'required|integer',
                'diaSemana.*' => 'required|in:Lunes,Martes,Miércoles,Jueves,Viernes',
                'tramoHorario' => 'required|in:' . implode(',', $tramoString),
                'repetir' => 'required|boolean',
                'repeticiones' => 'required|integer',
            ];

            //Mensaje en caso de error de verificacion
            $mensaje = [
                'required' => 'El :attribute es obligatorio',

            ];

            //Validacion del tramo horario enviado
            if (strpos(request()->tramoHorario, ' --- ') === false) {
                return back()->with('error', 'El tramo horario es inválido.');
            }

            //Validacion de los datos con sus requisitos y sus mensajes de validacion
            $this->validate($request, $campos, $mensaje);


            //Arrays necesarios
            $daysConversion = [
                'Lunes' => 'Monday',
                'Martes' => 'Tuesday',
                'Miércoles' => 'Wednesday',
                'Jueves' => 'Thursday',
                'Viernes' => 'Friday',
                'Sábado' => 'Saturday',
                'Domingo' => 'Sunday'
            ];

            $diasEspañol = [
                'Monday' => 'Lunes',
                'Tuesday' => 'Martes',
                'Wednesday' => 'Miércoles',
                'Thursday' => 'Jueves',
                'Friday' => 'Viernes',
                'Saturday' => 'Sábado',
                'Sunday' => 'Domingo'
            ];

            $daysOfWeek = [
                'Monday' => 0,
                'Tuesday' => 1,
                'Wednesday' => 2,
                'Thursday' => 3,
                'Friday' => 4,
                'Saturday' => 5,
                'Sunday' => 6,
            ];
            //Informacion del tramo horario
            $tramo = explode(' --- ', request()->tramoHorario);

            //Asociando cada parte a su hora correspondiente
            $horaInicio = $tramo[0];
            $horaFin = $tramo[1];

            // Datos básicos del horario sin incluir los días, token, ni repetición.
            $datosHorarioBase = request()->except('_token', 'tramoHorario', 'diaSemana', 'repetir', 'repeticiones');

            //Establece las horas de inicio y fin obtenidas
            $datosHorarioBase['horaInicio'] = $horaInicio;
            $datosHorarioBase['horaFin'] = $horaFin;


            // Días seleccionados y número de repeticiones.
            $diasSeleccionados = $request->input('diaSemana');
            //dump($diasSeleccionados);
            $repeticiones = $request->input('repeticiones');

            //El numero de registros que se va a guardar en la base de datos
            $numeroRegistros = $repeticiones + 1;



            $fecha = new DateTime($request->input('primerDia')); //Obtener la fecha seleccionada como primer dia
            $fechaInicio = clone $fecha; //Clona la variable para no perder su valor en el futuro
            $fechaDia = $fechaInicio->format('N'); //Devuelve en forma numerica Lunes:1 Domingo:7

            $primerDia = $fecha->modify('-' . ($fechaDia - 1) . ' days'); //Obtiene el valor del primer dia de la semana
            $primerDia = $primerDia->format('Y-m-d'); //Pasa a formato fecha
            //dump($fechaInicio);
            $primerDiaSemana = new DateTime($primerDia); //Creamos el valor de primer dia de la semana






            //Obtiene el dia correspondiente a esa fecha
            $diaIngresado = $fechaInicio->format('l');
            //debug
            //dump($diaIngresado);

            //Convierte los dias seleccionados (dados en español) al ingles
            $diasSeleccionadosInEnglish = array_map(function ($dia) use ($daysConversion) {
                return $daysConversion[$dia];
            }, $diasSeleccionados);
            //Valida que la fecha sea uno de los dias seleccionados
            if (!in_array($diaIngresado, $diasSeleccionadosInEnglish)) {
                return back()->with('error', 'La fecha seleccionada no coincide con ninguno de los días seleccionados.');
            }

            //dump($diaIngresado !== $diasSeleccionadosInEnglish[0]);
            //Comprobamos si el primer dia seleccionado no coincide con la fecha dada
            if ($diaIngresado !== $diasSeleccionadosInEnglish[0]) {
                $datosHorario = $datosHorarioBase; //Asigna los datos base a la variable nueva
                $cumplido = false; //variable para el flujo de la funcion

                foreach ($diasSeleccionadosInEnglish as $dia) {
                    $repeticiones = $request->input('repeticiones');
                    $numeroRegistros = $repeticiones + 1;
                    //dump($repeticiones, $numeroRegistros);
                    //dump($dia);
                    //Creamos array para cada dia semanal
                    //Averiguamos el dia del foreach para asignar al nombre del array
                    $arrayNombre = "array" . $dia;
                    //dump($arrayNombre);
                    $$arrayNombre = [];
                    $numeroDia = $daysOfWeek[$dia];
                    ////dump($numeroDia);
                    $diaUnoSemana = clone $primerDiaSemana; //Clona para no perder el valor
                    $fechaDiaCorrespondiente = $diaUnoSemana->modify('+' . $numeroDia . ' days');
                    //dump($diaUnoSemana);

                    //dump($fechaDiaCorrespondiente);
                    //si el dia no conincide con la fecha y aun no se ha cumplido
                    if ($dia != $diaIngresado && !$cumplido) {

resources/views/horarios/create.blade.php
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Gestor de Gruposs - Chus-Álvarez-Pilates</title>
</head>

<body>
    @extends('layouts.app', ['modo' => 'Horarios'])

    @section('content')
        <div class="container">
            <form class="row" action="{{ url('/horarios') }}" method="POST" enctype="multipart/form-data">
                @csrf

                @include('horarios.form', ['modo' => 'Crear'])
            </form>
        </div>
    @endsection
</body>

</html>

resources/views/horarios/edit.blade.php
@extends('layouts.app', ['modo' => 'Editando horario'])

@section('content')
    <div class="container">

        <form class="row" action="{{ url('/horarios/' . $horario->id) }}" method="POST" enctype="multipart/form-data">
            @csrf
            {{ method_field('PATCH') }}
            @include('horarios.form', ['modo' => 'Editar'])
        </form>
        <form action="{{ route('horarios.destroy', $horario->id) }}" method="POST">
            @csrf
            @method('DELETE')
            <button type="submit">Borrar registro</button>
        </form>

    </div>
@endsection

resources/views/horarios/form.blade.php
       <h1>{{ $modo }} Horario</h1>

       {{-- Para poder mostrar los mensajes de error --}}

       @if (count($errors) > 0)
           <div class="alert alert-danger" role="alert">
               <ul>
                   @foreach ($errors->all() as $error)
                       <li> {{ $error }}</li>
                   @endforeach
               </ul>
           </div>
       @endif
       <!-- Lista desplegable para Clases -->
       <label for="codigoClase">Clase: </label>
       <select name="codigoClase" class="form-control">
           @foreach ($clases as $clase)
               <option value="{{ $clase->id }}"
                   {{ isset($horario->codigoClase) && $horario->codigoClase == $clase->id ? 'selected' : '' }}>
                   {{ $clase->id }} {{ $clase->nombre }}</option>
           @endforeach
       </select>

       <!-- Lista desplegable para Empleados -->
       <label for="codigoEmpleado">Empleado: </label>
       <select name="codigoEmpleado" class="form-control">
           @foreach ($empleados as $empleado)
               <option value="{{ $empleado->id }}"
                   {{ isset($horario->codigoEmpleado) && $horario->codigoEmpleado == $empleado->id ? 'selected' : '' }}>
                   {{ $empleado->id }} {{ $empleado->nombre }}</option>
           @endforeach
       </select>

       <!-- Lista desplegable para Grupos -->
       <label for="codigoGrupo">Grupo: </label>
       <select name="codigoGrupo" class="form-control">
           @foreach ($grupos as $grupo)
               <option value="{{ $grupo->id }}"
                   {{ isset($horario->codigoGrupo) && $horario->codigoGrupo == $grupo->id ? 'selected' : '' }}>
                   {{ $grupo->id }} {{ $grupo->nombre }}</option>
           @endforeach
       </select>


       <div class="form-group">
       
           <label>Días de la semana:</label>
           <div>
               <input type="checkbox" id="lunes" name="diaSemana[]" value="Lunes" {{isset($datos['dia']) && $datos['dia'] === 'Lunes' ? 'checked' : ''}}>
               <label for="lunes">Lunes</label>
           </div>
           <div>
               <input type="checkbox" id="martes" name="diaSemana[]" value="Martes" {{isset($datos['dia']) && $datos['dia'] === 'Martes' ? 'checked' : ''}}>
               <label for="martes">Martes</label>
           </div>
           <div>
               <input type="checkbox" id="miercoles" name="diaSemana[]" value="Miércoles" {{isset($datos['dia']) && $datos['dia'] === 'Miércoles' ? 'checked' : ''}}>
               <label for="miercoles">Miércoles</label>
           </div>
           <div>
               <input type="checkbox" id="jueves" name="diaSemana[]" value="Jueves" {{isset($datos['dia']) && $datos['dia'] === 'Jueves' ? 'checked' : ''}}>
               <label for="jueves">Jueves</label>
           </div>
           <div>
               <input type="checkbox" id="viernes" name="diaSemana[]" value="Viernes" {{isset($datos['dia']) && $datos['dia'] === 'Viernes' ? 'checked' : ''}}>
               <label for="viernes">Viernes</label>
           </div>
       </div>


       <!-- Tramos horarios establecidos:
            Tramo 1: 10:00 --- 11:20
            Tramo 2: 11:30 --- 12:50
            Tramo 3: 13:00 --- 14:20
            Tramo 4: 15:00 --- 16:20
            Tramo 5: 16:30 --- 17:50
            Tramo 6: 18:00 --- 19:20
            Tramo 7: 19:30 --- 20:50

       -->
       <div class="form-group">
           <select name="tramoHorario" id="tramoHorario">
               <option value="default">Elige un tramo horario</option>
               <option value="10:00 --- 11:20"
                   {{ isset($datos['tramo']) && $datos['tramo'] == '10:00 --- 11:20' ? 'selected' : '' }}>10:00 ---
                   11:20</option>
               <option value="11:30 --- 12:50"
                   {{ isset($datos['tramo']) && $datos['tramo'] == '11:30 --- 12:50' ? 'selected' : '' }}>11:30 ---
                   12:50</option>
               <option value="13:00 --- 14:20"
                   {{ isset($datos['tramo']) && $datos['tramo'] == '13:00 --- 14:20' ? 'selected' : '' }}>13:00 ---
                   14:20</option>
               <option value="15:00 --- 16:20"
                   {{ isset($datos['tramo']) && $datos['tramo'] == '15:00 --- 16:20' ? 'selected' : '' }}>15:00 ---
                   16:20</option>
               <option value="16:30 --- 17:50"
                   {{ isset($datos['tramo']) && $datos['tramo'] == '16:30 --- 17:50' ? 'selected' : '' }}>16:30 ---
                   17:50</option>
               <option value="18:00 --- 19:20"
                   {{ isset($datos['tramo']) && $datos['tramo'] == '18:00 --- 19:20' ? 'selected' : '' }}>18:00 ---
                   19:20</option>
               <option value="19:30 --- 20:50"
                   {{ isset($datos['tramo']) && $datos['tramo'] == '19:30 --- 20:50' ? 'selected' : '' }}>19:30 ---
                   20:50</option>
           </select>
       </div>



       <div class="form-group">
           <label for="primerDia">Primer día:</label>
           <input type="date" id="primerDia" name="primerDia" required
               value="{{ isset($datos['fecha']) ? $datos['fecha'] : '' }}">
       </div>

       <div class="form-group">
           <label for="repetir">Repetir: </label>
           <select name="repetir" id="repetir">
               <option value="1"{{ isset($horario->repetir) && $horario->repetir == 1 ? 'selected' : '' }}>Si
               </option>
               <option
                   value="0"{{ !isset($horario->repetir) || (isset($horario->repetir) && $horario->repetir == 0) ? 'selected' : '' }}>
                   No</option>
           </select>

       </div>


       <div class="form-group">
           <label for="repeticiones">Repeticiones: </label>
           <input type="number" class="form-control" name="repeticiones" id="repeticiones"
               value="{{ isset($horario->repeticiones) ? $horario->repeticiones : old('repeticiones') }}">
       </div>

       <div class="form-group">
           <input class="btn btn-success" type="submit" value="{{ $modo }} datos Horario">
           <a class="btn btn-primary" href="{{ url('horarios/') }}">Regresar</a>
       </div>

resources/views/horarios/index.blade.php
<!DOCTYPE html>
<html lang="en">
<?php
use Carbon\Carbon;

?>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    
    @extends('layouts.app', ['modo' => 'Horarios'])
    @section('content')
        <div class="container">
            <a href="{{ url('horarios/create') }}">Crear nuevo registro</a>
            <form action="{{ url('/horarios/') }}" method="GET">
                <label for="semana">Selecciona la semana:</label>
                <input type="week" name="semana">
                <button type="submit">Mostrar</button>
            </form>
            @if (isset($currentDate))
                <div class="navigation-buttons">
                    <a href="{{ url('/horarios?date=' .$currentDate->copy()->subWeek()->toDateString()) }}">Semana
                        Anterior</a>
                    <span>Semana del {{ $currentDate->startOfWeek()->toFormattedDateString() }} al
                        {{ $currentDate->endOfWeek()->toFormattedDateString() }}</span>
                    <a href="{{ url('/horarios?date=' .$currentDate->copy()->addWeek()->toDateString()) }}">Semana
                        Posterior</a>
                </div>
            @endif
            <h3>Semana seleccionada</h3>
            <table class="table text-center align-middle table-striped-columns table-responsive fs-6"
                style="left:5%; width:100%">
                <thead>
                    <tr>
                        <th>Tramos Horarios</th>
                        @foreach (['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes'] as $index => $dia)
                            <th>
                                {{ $dia }}<br>
                                {{ $currentDate->startOfWeek()->addDays($index)->format('Y-m-d') }}
                            </th>
                        @endforeach
                    </tr>
                </thead>
                <tbody>
                    @foreach (['10:00 --- 11:20', '11:30 --- 12:50', '13:00 --- 14:20', '15:00 --- 16:20', '16:30 --- 17:50', '18:00 --- 19:20', '19:30 --- 20:50'] as $tramo)
                        <tr>
                            <td>{{ $tramo }}</td>
                            @foreach (['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes'] as $indexDia => $dia)
                                <td>
                                    @php
                                        $fechaDia = $currentDate
                                            ->copy()
                                            ->startOfWeek()
                                            ->addDays($indexDia)
                                            ->format('Y-m-d');
                                        $matchedHorario = $horarios->first(function ($horario) use ($dia, $tramo) {
                                            return $horario->diaSemana == $dia && substr($horario->horaInicio, 0, 5) . ' --- ' . substr($horario->horaFin, 0, 5) == $tramo;
                                        });
                                    @endphp

                                    @if ($matchedHorario)
                                    <?php
                                        $idHorario = $matchedHorario->id
                                    ?>
                                        <a href="{{ url('horarios/edit', ['dia' => $dia,'tramo' => $tramo,'fecha' => $fechaDia, 'id' => $idHorario])}}">
                                        {{ $matchedHorario->clase->nombre }}
                                        </a>
                                    @else
                                        <a href="{{ url('horarios/create', ['dia' => $dia,'tramo' => $tramo,'fecha' => $fechaDia]) }}">Crear</a>
                                    @endif
                                </td>
                            @endforeach
                        </tr>
                    @endforeach

                </tbody>


            </table>{{ $horarios }}
        </div>
    @endsection
</body>





</html>